name: Houston
options:
  usesTabs: false
  indentWidth: 2
  tabWidth: 2
  deploymentTarget:
    macOS: "11.0"
configFiles:
  Debug: XcodeGen/Debug.xcconfig
  Release: XcodeGen/Release.xcconfig
settingGroups:
  app:
    CODE_SIGN_IDENTITY: "Apple Development"
    CODE_SIGN_STYLE: "Automatic"
    DEVELOPMENT_TEAM: ${TEAM_ID}
targets:
  Houston:
    type: application
    platform: "macOS"
    sources:
      - Sources
    settings:
      groups: [app]
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: "AppIcon"
        CURRENT_PROJECT_VERSION: 4
        ENABLE_HARDENED_RUNTIME: true
        INFOPLIST_FILE: "Resources/Info.plist"
        MARKETING_VERSION: 0.0.4
        PRODUCT_BUNDLE_IDENTIFIER: "com.zenangst.Houston"
        PRODUCT_NAME: "Houston"
    entitlements:
      path: Resources/com.zenangst.Houston.entitlements
      properties:
        com.apple.security.automation.apple-events: true
schemes:
  Houston:
    build:
      targets:
        Houston: all
    run:
      config: Debug
      environmentVariables:
        SOURCE_ROOT: $(SRCROOT)
    test:
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      revealArchiveInOrganizer: false
fileGroups:
  - .gitignore
  - build_pipeline.sh
  - project.yml
  - configure.sh
  - Scripts
